### Test PostgREST (via VSCode - REST Client extension)

GET http://localhost:3000/model HTTP/1.1
Accept: application/vnd.pgrst.object+json
Accept: application/json

###

PATCH http://localhost:3000/model HTTP/1.1
Accept: application/vnd.pgrst.object+json
Accept: application/json
Content-Type: application/json
Prefer: return=representation

{
  "uid": 0,
  "field": "",
  "visibility": "All",
  "entries": []
}
